/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { OBJLoader } from 'three/examples/jsm/loaders/OBJLoader'
import { useLoader } from '@react-three/fiber';


import React from "react";
import {pointLight} from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useRef } from 'react';

export function Chair({ opacity, ...props }) {

  
  const helix = useRef();
  useFrame((_state, delta) => {
    helix.current.rotation.y += delta * 0.5;
  });


  const obj = useLoader(OBJLoader, './models/cloud/chair.obj')
  console.log(obj)
  return (
    <group {...props} dispose={null} ref={helix}>
       <mesh
        // rotation={[1, 0, 1]}
        receiveShadow
        geometry={obj.children[0].geometry}
        material={obj.children[0].material}
      >
        <meshStandardMaterial
        opacity={0.2}
        color={"black"}
        intensity={10}
       />
      </mesh>


      <mesh
        // rotation={[1, 0, 1]}
        receiveShadow
        geometry={obj.children[1].geometry}
        material={obj.children[1].material}
        >
        <meshStandardMaterial
        {...obj.children[0].material["lambert2SG.001"]}
        transparent
        opacity={1}
        color={"orange"}
        intensity={10}
       />
      </mesh>
      
      <mesh
        // rotation={[1, 0, 1]}
        receiveShadow
        geometry={obj.children[3].geometry}
        material={obj.children[3].material}
        >
        <meshStandardMaterial
        {...obj.children[0].material["lambert2SG.001"]}
        transparent
        opacity={1}
        color={"black"}
        intensity={100}
       />
      </mesh>


      <mesh
        receiveShadow
        geometry={obj.children[4].geometry}
        material={obj.children[4].material}
      >
        <meshStandardMaterial
        {...obj.children[0].material["lambert2SG.001"]}
        transparent
        opacity={1}
        color={"green"}
        intensity={100}
       />
      </mesh>


      <mesh
        receiveShadow
        geometry={obj.children[5].geometry}
        material={obj.children[5].material}
        >
        <meshStandardMaterial
        {...obj.children[0].material["lambert2SG.001"]}
        transparent
        opacity={1}
        color={"red"}
        intensity={100}
       />
      </mesh>


      <mesh
        receiveShadow
        geometry={obj.children[7].geometry}
        material={obj.children[7].material}
        >
        <meshStandardMaterial
        {...obj.children[0].material["lambert2SG.001"]}
        transparent
        opacity={1}
        color={"black"}
        intensity={100}
       />
      </mesh>

      
    </group>
  );
}

